# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0d424a13814fd19d2125d2b79a1fd46578b45b07a282802e77a39bacb48d1e41a4acefa99ed82794e293346f16ac1fc91cda2b300080e4fb7f0aaeda0b6b8d1

test:
  secret_key_base: 4d6e2814248c38aaff40f534892f7763e5c5cee45355449648664d50d351588aead179b881bcc1064d8f3676b338f7dae4519626d5e3dcc60b946ffbf6c57447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
